### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException when adding new word

### ISSUE THREAD

**Issue by randomowo** [randomowo/SuffixTree#1]
When you try to add a few long strings, then throws *java.lang.StringIndexOutOfBoundsException*
# example:
*-w a
-w asdfghjlkzxcvbnm,.qwertyuio
-w asdfghdgfjkdyrjaetn
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 1
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
        at java.base/java.lang.String.charAt(String.java:693)
        at main.tree.SuffixTree.addSuffix(SuffixTree.kt:41)
        at main.tree.SuffixTree.addWord(SuffixTree.kt:14)
        at main.MainKt$choice$1.invoke(Main.kt:42)
        at main.MainKt$choice$1.invoke(Main.kt)
        at main.MainKt.ifErr(Main.kt:60)
        at main.MainKt.choice(Main.kt:42)
        at main.MainKt.main(Main.kt:24)*

**Comment by randomowo** [comment]
same exeption when you try to add word with the same characters at the end of the word

**Comment by randomowo** [comment]
FIXED
